language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
script: 
    - nosetests

notifications:
  webhooks: http://104.131.120.228:8080/hubot/travisci/general
  on_start: true
